### ISSUE TITLE
How to pass headers & body params

### ISSUE THREAD

**Issue by Pauly24** [Crypto-APIs/Node.js-Library#12]
Sorry I must be missing something here, for example with caClient.BC.BTC.transaction.newTransaction(), it links back to the docs here https://docs.cryptoapis.io/rest-apis/blockchain-as-a-service-apis/btc/index#btc-transactions-new-transactions
but there is no talk of this sdk, or how to pass variables through that functions?

**Comment by Crypto-APIs** [comment]
@Pauly24, thank you for your feedback .
The docs are being revisited at the moment and the current visible version is an example of the capabilities. It does not offer detailed description of the required/optional parameters as an adoption period needed to have passed to see if the users were more comfortable with this format or the [old one](https://github.com/Crypto-APIs/Node.js-Library/blob/master/README--deprecated.md) of the docs before deciding which one should we support.

**Comment by Crypto-APIs** [comment]
We do not support arbitrary headers passed to calls in our system. The only thing you should need to use this library is the [API key](https://docs.cryptoapis.io/authentication/index#authentication) which is needed only once during the instantiation of the library and is used for every call from there on transparently.
As for body parameters, the previous comment covers that.

**Comment by Crypto-APIs** [comment]
[README updated](https://github.com/Crypto-APIs/Node.js-Library/tree/4.4.0). Closing this. Feel free to reopen it in case of further issues
