### ISSUE TITLE
ERR_HTTP_INVALID_HEADER_VALUE

### ISSUE THREAD

**Issue by danedyy** [Crypto-APIs/Node.js-Library#13]
hello,
just started getting this on my previously working code.
i need you help
  "error": {
        "code": "ERR_HTTP_INVALID_HEADER_VALUE"
    }

**Comment by Crypto-APIs** [comment]
@danedyy can you give some details on what calls do you receive this?

**Comment by Crypto-APIs** [comment]
Closing this now. Feel free to reopen it if you encounter the issue
