### ISSUE TITLE
XRP API added in cryptoapis.io website

### ISSUE THREAD

**Issue by bagherani** [Crypto-APIs/Node.js-Library#18]
Due to [this link](https://docs.cryptoapis.io/rest-apis/blockchain-as-a-service-apis/xrp/index#general-information) XRP coins API are now available.
Please update the source.
![2020-07-21_091537](https://user-images.githubusercontent.com/12948334/88013874-c3ae3a00-cb32-11ea-8f86-112730cb1d2a.png)

**Comment by Crypto-APIs** [comment]
It is live now with version [4.5](https://github.com/Crypto-APIs/Node.js-Library/releases/tag/4.5.0). You can update the lib and use XRP
